pr:
  autoCancel: true

stages:
- stage: 'lint'
  trigger:
    branches:
      exclude:
        - master
    pr:
      - master

  jobs:
  - job: 'lint'  
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      maxParallel: 8

    steps:
    - script: |
        git remote add upstream https://github.com/bioconda/bioconda-recipes
        git checkout master
        git pull upstream master
        source=$(Build.SourceBranch)
        git checkout ${source#"refs/heads/"}

    - bash: echo "##vso[task.prependpath]$CONDA/bin"
      displayName: Add conda to PATH

    - bash: |
        which conda
        wget https://raw.githubusercontent.com/bioconda/bioconda-common/master/common.sh
      displayName: Fetch common.sh

    - task: Cache@2
      inputs:
        path: "/usr/share/miniconda/envs/bioconda"
        key: '"$(Agent.OS)" | **/common.sh'
        cacheHitVar: CACHE_RESTORED
      displayName: Restore cache

    - script: .azure-pipelines/createEnv.py
      condition: ne(variables.CACHE_RESTORED, 'true')
      displayName: Install bioconda-utils

    - bash: |
          source activate bioconda
          set -e
          bioconda-utils lint --loglevel debug --full-report --git-range master HEAD
      displayName: Lint

- stage: 'test_linux'
  trigger:
    branches:
      exclude:
        - master
    pr:
      - master
  jobs:
  - job: 'test_linux'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      maxParallel: 8

    steps:
      - script: |
          git remote add upstream https://github.com/bioconda/bioconda-recipes
          git checkout master
          git pull upstream master
          source=$(Build.SourceBranch)
          git checkout ${source#"refs/heads/"}

      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH

      - bash: |
          which conda
          wget https://raw.githubusercontent.com/bioconda/bioconda-common/master/common.sh
        displayName: Fetch common.sh

      - task: Cache@2
        inputs:
          path: "/usr/share/miniconda/envs/bioconda"
          key: '"$(Agent.OS)" | **/common.sh'
          cacheHitVar: CACHE_RESTORED
        displayName: Restore cache

      - script: .azure-pipelines/createEnv.py
        condition: ne(variables.CACHE_RESTORED, 'true')
        displayName: Install bioconda-utils

      - bash: |
          set -e
          source activate bioconda
          docker pull quay.io/dpryan79/mulled_container:latest
          ls -l /usr/share/miniconda/envs/bioconda
          conda install conda-build
          bioconda-utils build recipes config.yml \
              --docker --mulled-test \
              --git-range master HEAD
          docker rmi quay.io/dpryan79/mulled_container:latest
        displayName: Test
