{% set version = "0.2.3" %}
{% set sha256 = "61544b53b5619e60d0c4a4300b3d491079e42ffe927a4f867f5d2da00e124a36" %}

package:
  name: wally
  version: '{{ version }}'

source:
  url: https://github.com/tobiasrausch/wally/archive/v{{ version }}.tar.gz
  sha256: '{{ sha256 }}'
  patches:
    - Makefile.patch

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - cmake
    - autoconf
    - automake
  host:
    - libpng
    - zlib
    - bzip2
    - xz
    - boost-cpp
    - opencv >=4.5.3
    - htslib
  run:
    - libpng
    - zlib
    - bzip2
    - xz
    - boost-cpp
    - opencv >=4.5.3
    - htslib

test:
  commands:
    - wally --help

about:
  home: https://github.com/tobiasrausch/wally
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Fast visualizations of aligned sequencing reads and genomic variants.
